### ISSUE TITLE
No output is printed after running the python file

### ISSUE THREAD

**Issue by hethkar** [sparkgeo/awsstats#1]
i did export  the credentials as 
export AWS_ACCESS_KEY= MY_KEY
export AWS_ACCESS_SECRET= MY_SECRET

In the same Directory as ec2.py i created a instance.py file with below contents
import ec2
for timestamp, value in ec2.get_avg_cpu('i-1212jh1j212v'):
    print('{}: {}'.format(timestamp, value))

This does not give me any output as mentioned in the Readme.

**Comment by gridcell** [comment]
Hey @hethkar, yeah I'm seeing that as well.  I've made some tweaks and updated the docs to reflect.  The main thing is sticking to AWS's environment variable naming conventions.

`AWS_ACCESS_KEY_ID =`
`AWS_SECRET_ACCESS_KEY=`
